[project]
name = "documentz-worker"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "documentz-application",
    "documentz-infrastructure",
    "procrastinate==3.10.0",
]

[build-system]
requires = ["hatchling==1.32.4"]
build-backend = "hatchling.build"

[tool.uv.sources]
documentz-application = { workspace = true }
documentz-infrastructure = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/documentz_worker"]
